/* eslint-disable max-lines */
import { UseTranslations } from '@I18n/useTypedTranslations';

interface TechCategory {
  categoryTitle: string;
  items: string[];
}

export const getTechList = (t: UseTranslations<'TechISpeak'>): TechCategory[] => [
  {
    categoryTitle: t('languagesTitle'),
    items: [
      'JavaScript',
      'TypeScript',
      'Node.js',
      'Java',
      'C#',
      'Groovy',
      'Swift',
      'Objective-C',
      'Shell',
      'Bicep',
      'YAML',
    ],
  },
  {
    categoryTitle: t('frontendFrameworksTitle'),
    items: [
      'React',
      'Next.js',
      'Angular',
      'Redux',
      'Redux Toolkit',
      'Redux Persist',
      'Redux Saga',
      'Redux Thunk',
      'React Router',
      'React Hook Form',
      'Formik',
      'React Query',
      'Material-UI',
      'Bootstrap',
      'Styled Components',
      'Emotion',
      'GraphQL',
      'Apollo',
      'Expo',
      'sass',
    ],
  },
  {
    categoryTitle: t('backendFrameworksTitle'),
    items: ['NestJS', 'Express', 'Spring Boot', 'Dotnet Core', 'SignalR', 'Socket.io', 'passport', 'pm2'],
  },
  {
    categoryTitle: t('databaseTitle'),
    items: [
      'PostgreSQL',
      'SQL Server',
      'MongoDB',
      'Mongoose',
      'Redis',
      'Firebase Realtime Database',
      'Firebase Firestore',
      'Azure SQL Edge',
      'Azure Database for PostgreSQL',
    ],
  },
  {
    categoryTitle: t('devOpsTitle'),
    items: [
      'Docker',
      'Jenkins',
      'GitHub Actions',
      'Bitbucket',
      'CircleCI',
      'TravisCI',
      'Azure DevOps',
      'SonarQube',
      'Artifactory',
    ],
  },
  {
    categoryTitle: t('monitoringTitle'),
    items: [
      'Sentry',
      'Fullstory',
      'Intercom',
      'Posthog',
      'Hotjar',
      'Google Analytics',
      'Google Tag Manager',
      'axe-core',
    ],
  },
  {
    categoryTitle: t('communicationAndPaymentsTitle'),
    items: [
      'Sendgrid',
      'Twilio',
      'nodemailer',
      'Swagger',
      'Postman',
      'Sendbird',
      'Stripe',
      'Chargebee',
      'DocuSign',
      'HelloSign',
    ],
  },
  {
    categoryTitle: t('mediaHandlingTitle'),
    items: ['Box', 'Photoshelter', 'Azure Blog Storage', 'FFmpeg', 'Amazon S3'],
  },
  {
    categoryTitle: t('testingTitle'),
    items: [
      'Jest',
      'React Testing Library',
      'Cypress',
      'Storybook',
      'Playwright',
      'Puppeteer',
      'Lighthouse',
      'Qase',
      'supertest',
      'Cucumber',
      'Enzyme',
      'Mocha',
    ],
  },
  {
    categoryTitle: t('buildTitle'),
    items: [
      'Webpack',
      'Vite',
      'Rollup',
      'Babel',
      'npm',
      'Yarn',
      'pnpm',
      'ESLint',
      'Prettier',
      'Husky',
      'Lint Staged',
      'Commitlint',
      'Conventional Commits',
      'Semantic Release',
      'Commander',
      'Lodash',
      'Validator',
      'date-fns',
      'Moment.js',
      'Day.js',
      'next-intl',
      'react-intl',
      'Formatjs',
      'notistack',
      'yup',
      'swr',
      'openai',
      'openapi-generator',
      'class-validator',
      'class-transformer',
      'reselect',
      'Okta',
      'Cheerio',
    ],
  },
  {
    categoryTitle: t('azureTitle'),
    items: [
      'Azure AI Translator',
      'Azure OpenAI Service',
      'Azure App Service',
      'Azure Static Web Apps',
      'Azure Functions',
      'Azure DevOps',
      'Azure Pipelines',
      'Azure Artifacts',
      'Azure Repos',
      'Microsoft Entra ID',
      'Azure Service Bus',
      'Azure Resource Manager',
      'Azure CDN',
      'Azure Front Door',
      'Azure Streaming',
      'Azure DNS',
      'Azure WAF',
      'Azure Key Vault',
      'Azure AI Search',
    ],
  },
  {
    categoryTitle: t('awsTitle'),
    items: [
      'AWS EC2',
      'AWS S3',
      'AWS Lambda',
      'AWS SQS',
      'AWS SNS',
      'AWS SES',
      'AWS Amplify',
      'AWS CloudFormation',
      'AWS CodeBuild',
      'AWS CodeDeploy',
      'AWS Elastic Beanstalk',
      'AWS Identity and Access Management (IAM)',
      'AWS KMS',
    ],
  },
  {
    categoryTitle: t('gcpTitle'),
    items: ['GCP Compute', 'Firebase Cloud Functions', 'Firebase Authentication', 'Firebase Cloud Storage'],
  },
];
